name: Checks

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: '🔑 Checkout'
        uses: actions/checkout@v5

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: 'Install Dependencies'
        run: bun install

      - name: 'Lint, Typecheck, Build'
        run: |
          bun x @biomejs/biome check . --reporter='github'
          bun tsc --project tsconfig.json --noEmit

          bun x tsdown --config='tsdown.config.ts'
          
          bun x publint@latest
          bun x @arethetypeswrong/cli@latest --pack . --ignore-rules='false-cjs' --ignore-rules='cjs-resolves-to-esm'
